version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: rising_bsm
      POSTGRES_USER: rising_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rising_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: