services:
  # Database service
  db:
    image: postgres:13
    container_name: rising-bsm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rising_bsm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rising-bsm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rising-bsm-backend
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rising-bsm-network

  # Frontend service 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rising-bsm-frontend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rising-bsm-network
    command: npm run dev

networks:
  rising-bsm-network:
    driver: bridge

volumes:
  postgres_data: