version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: rising_bsm
      POSTGRES_USER: rising_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=rising_user
      - DB_PASSWORD=your_secure_password
      - DB_DATABASE=rising_bsm
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data: