services:
  # Database service
  db:
    image: postgres:13
    container_name: rising-bsm-db-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: rising_bsm_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rising-bsm-network-prod
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend service (production mode)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rising-bsm-frontend-prod
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rising-bsm-network-prod
    restart: always

networks:
  rising-bsm-network-prod:
    driver: bridge

volumes:
  postgres_data_prod: