version: '3.8'

services:
  # Database service
  db:
    image: postgres:13
    container_name: rising-bsm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rising_bsm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rising-bsm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rising-bsm-backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rising_bsm?schema=public
      - JWT_SECRET=your-default-super-secret-key-change-in-production
      - JWT_REFRESH_SECRET=your-refresh-default-key-change-in-production
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - rising-bsm-network
    command: >
      sh -c "npx prisma generate && npm run dev"

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rising-bsm-frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rising-bsm-network
    command: npm run dev

networks:
  rising-bsm-network:
    driver: bridge

volumes:
  postgres_data: