openapi: 3.0.0
info:
  title: Rising BSM API
  version: 1.0.0
  description: |
    Backend API for Rising Business Service Management
    
    This API provides endpoints for managing customers, projects, appointments, 
    services, and other business operations for the Rising BSM platform.
  contact:
    name: API Support
    email: support@example.com
  license:
    name: Proprietary
    url: https://example.com/license

servers:
  - url: http://localhost:5000/API/v1
    description: Local development server
  - url: https://api.example.com/API/v1
    description: Production server

# Tags for organizing operations
tags:
  - name: Authentication
    description: Authentication and user access operations
  - name: Users
    description: User management operations
  - name: Notifications
    description: User notification operations
  - name: Customers
    description: Customer management
#  - name: Projects
#    description: Project management
#  - name: Appointments
#    description: Appointment scheduling and management
#  - name: Services
#    description: Service management
  - name: Requests
    description: Contact request management
  - name: Profile
    description: User profile management
  - name: Dashboard
    description: Dashboard related operations
  - name: Settings
    description: User and system settings
#  - name: Public
#    description: Public accessible endpoints
  - name: System
    description: System and health check endpoints

# Security schemes
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  # Common schemas
  schemas:
    # Import common schemas from separate files
    Error:
      $ref: './schemas/error.yaml#/Error'
    ValidationError:
      $ref: './schemas/error.yaml#/ValidationError'
    Pagination:
      $ref: './schemas/common.yaml#/Pagination'
    SuccessResponse:
      $ref: './schemas/common.yaml#/SuccessResponse'
    
  # Common responses
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ForbiddenError:
      description: Insufficient permissions to access the resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

# Default security requirement
security:
  - bearerAuth: []

# Paths are organized and imported from separate files
paths:
  # Authentication
  /login:
    $ref: './paths/auth.yaml#/login'
  /auth/refresh-token:
    $ref: './paths/auth.yaml#/refresh-token'
  /auth/forgot-password:
    $ref: './paths/auth.yaml#/forgot-password'
  /auth/reset-token/{token}:
    $ref: './paths/auth.yaml#/validate-reset-token'
  /auth/reset-password/{token}:
    $ref: './paths/auth.yaml#/reset-password'
  /auth/logout:
    $ref: './paths/auth.yaml#/logout'
  /auth/dev/reset-token:
    $ref: './paths/auth.yaml#/get-reset-token'

  # Users
  /users:
    $ref: './paths/user.yaml#/users'
  /users/{id}:
    $ref: './paths/user.yaml#/users-id'
  /users/{id}/status:
    $ref: './paths/user.yaml#/users-id-status'

  # Notifications
  /notifications:
    $ref: './paths/notifications.yaml#/notifications'
  /notifications/read:
    $ref: './paths/notifications.yaml#/notifications-read'

  # Customers
  /customers:
    $ref: './paths/customers.yaml#/customers'
  /customers/statistics:
    $ref: './paths/customers.yaml#/customers-statistics'
  /customers/{id}:
    $ref: './paths/customers.yaml#/customers-id'
  /customers/{id}/notes:
    $ref: './paths/customers.yaml#/customers-id-notes'
  /customers/{id}/status:
    $ref: './paths/customers.yaml#/customers-id-status'
  /customers/search:
    $ref: './paths/customers.yaml#/customers-search'
  /customers/bulk-update:
    $ref: './paths/customers.yaml#/customers-bulk-update'
  /customers/export:
    $ref: './paths/customers.yaml#/customers-export'
  /customers/{id}/insights:
    $ref: './paths/customers.yaml#/customers-id-insights'
  /customers/{id}/similar:
    $ref: './paths/customers.yaml#/customers-id-similar'
  /customers/{id}/history:
    $ref: './paths/customers.yaml#/customers-id-history'

  # Projects (Zur Zeit nicht implementiert)
  # /projects:
  #   $ref: './paths/projects.yaml#/projects'
  # /projects/statistics:
  #   $ref: './paths/projects.yaml#/projects-statistics'
  # /projects/export:
  #   $ref: './paths/projects.yaml#/projects-export'
  # /projects/{id}:
  #   $ref: './paths/projects.yaml#/projects-id'
  # /projects/{id}/status:
  #   $ref: './paths/projects.yaml#/projects-id-status'
  # /projects/{id}/notes:
  #   $ref: './paths/projects.yaml#/projects-id-notes'

  # Appointments (Zur Zeit nicht implementiert)
  # /appointments:
  #   $ref: './paths/appointments.yaml#/appointments'
  # /appointments/{id}:
  #   $ref: './paths/appointments.yaml#/appointments-id'
  # /appointments/{id}/status:
  #   $ref: './paths/appointments.yaml#/appointments-id-status'
  # /appointments/{id}/notes:
  #   $ref: './paths/appointments.yaml#/appointments-id-notes'

  # Services (Zur Zeit nicht implementiert)
  # /services:
  #   $ref: './paths/services.yaml#/services'
  # /services/{id}:
  #   $ref: './paths/services.yaml#/services-id'
  # /services/{id}/status:
  #   $ref: './paths/services.yaml#/services-id-status'
  # /services/{id}/statistics:
  #   $ref: './paths/services.yaml#/services-id-statistics'

  # Requests
  /requests:
    $ref: './paths/requests.yaml#/requests'
  /requests/{id}:
    $ref: './paths/requests.yaml#/requests-id'
  /requests/{id}/status:
    $ref: './paths/requests.yaml#/requests-id-status'
  /requests/{id}/notes:
    $ref: './paths/requests.yaml#/requests-id-notes'
  /requests/{id}/assign:
    $ref: './paths/requests.yaml#/requests-id-assign'
  /requests/batch/status:
    $ref: './paths/requests.yaml#/requests-batch-status'
  /requests/export:
    $ref: './paths/requests.yaml#/requests-export'
  /requests/public:
    $ref: './paths/requests.yaml#/requests-public'
  
  # Public API
  # Hinweis: Nutzung von /requests/public empfohlen, /contacts wird in zukünftigen Versionen entfernt

  # Profile
  /profile/me:
    $ref: './paths/profile.yaml#/profile-me'
  /profile/me/password:
    $ref: './paths/profile.yaml#/profile-me-password'
  /profile/me/picture:
    $ref: './paths/profile.yaml#/profile-me-picture'
  /profile/me/activity:
    $ref: './paths/profile.yaml#/profile-me-activity'

  # Dashboard (Zur Zeit nicht implementiert)
  /dashboard:
    $ref: './paths/dashboard.yaml#/dashboard'
  /dashboard/stats:
    $ref: './paths/dashboard.yaml#/dashboard-stats'
  /dashboard/search:
    $ref: './paths/dashboard.yaml#/dashboard-search'

  # Settings
  /settings/user:
    $ref: './paths/settings.yaml#/settings-user'
  /settings/system:
    $ref: './paths/settings.yaml#/settings-system'

  # System
  /health:
    $ref: './paths/system.yaml#/health'
  /version:
    $ref: './paths/system.yaml#/version'