version: '3.8'

services:
  mcp-server:
    build: .
    container_name: bms-mcp-server
    command: python run_mcp.py
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mcp-network

  sse-server:
    build: .
    container_name: bms-sse-server
    command: python run_sse.py
    ports:
      - "${MCP_SERVER_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - mcp-network

  # Optional: N8N for testing
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=0.0.0.0
      - WEBHOOK_URL=http://n8n:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - mcp-network
    depends_on:
      - sse-server

networks:
  mcp-network:
    driver: bridge

volumes:
  n8n_data: