settings-user:
  get:
    tags:
      - Settings
    summary: Get user settings
    description: Retrieve current user's settings
    operationId: getUserSettings
    responses:
      '200':
        description: User settings
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                data:
                  $ref: '../schemas/settings.yaml#/UserSettings'
                message:
                  type: string
                  example: "User settings retrieved successfully"
                meta:
                  type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
      '401':
        $ref: '../openapi.yaml#/components/responses/UnauthorizedError'

  put:
    tags:
      - Settings
    summary: Update user settings
    description: Update current user's settings
    operationId: updateUserSettings
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/settings.yaml#/UserSettingsUpdate'
    responses:
      '200':
        description: Settings updated
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                data:
                  $ref: '../schemas/settings.yaml#/UserSettings'
                message:
                  type: string
                  example: "Settings updated successfully"
                meta:
                  type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
      '400':
        $ref: '../openapi.yaml#/components/responses/ValidationError'
      '401':
        $ref: '../openapi.yaml#/components/responses/UnauthorizedError'

settings-system:
  get:
    tags:
      - Settings
    summary: Get system settings
    description: Retrieve system settings (admin only)
    operationId: getSystemSettings
    responses:
      '200':
        description: System settings
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                data:
                  $ref: '../schemas/settings.yaml#/SystemSettings'
                message:
                  type: string
                  example: "System settings retrieved successfully"
                meta:
                  type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
      '401':
        $ref: '../openapi.yaml#/components/responses/UnauthorizedError'
      '403':
        $ref: '../openapi.yaml#/components/responses/ForbiddenError'

  put:
    tags:
      - Settings
    summary: Update system setting
    description: Update a specific system setting (admin only)
    operationId: updateSystemSetting
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - key
              - value
            properties:
              key:
                type: string
                description: Setting key
              value:
                type: string
                description: Setting value
              description:
                type: string
                description: Optional setting description
    responses:
      '200':
        description: Setting updated
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                data:
                  $ref: '../schemas/settings.yaml#/SystemSetting'
                message:
                  type: string
                  example: "System setting updated successfully"
                meta:
                  type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
      '400':
        $ref: '../openapi.yaml#/components/responses/ValidationError'
      '401':
        $ref: '../openapi.yaml#/components/responses/UnauthorizedError'
      '403':
        $ref: '../openapi.yaml#/components/responses/ForbiddenError'