name: rising_bsm
description: Rising BSM - Business Service Management mobile application
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # API and Network
  dio: ^5.3.3
  retrofit: ^4.0.3
  connectivity_plus: ^5.0.1
  json_annotation: ^4.8.1
  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.2
  equatable: ^2.0.5

  # Navigation
  go_router: ^12.0.1
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  intl: ^0.18.1

  # Others
  get_it: ^7.6.4
  logger: ^2.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  bloc_test: ^9.1.4
  mocktail: ^1.0.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
