UserSettings:
  type: object
  properties:
    language:
      type: string
      enum: [de, en]
      default: de
      description: Language preference
    darkMode:
      type: boolean
      default: false
      description: Dark mode preference
    emailNotifications:
      type: boolean
      default: true
      description: Email notifications preference
    pushNotifications:
      type: boolean
      default: false
      description: Push notifications preference
    notificationInterval:
      type: string
      enum: [immediate, daily, weekly]
      default: immediate
      description: Notification delivery interval

UserSettingsUpdate:
  type: object
  properties:
    language:
      type: string
      enum: [de, en]
      description: Language preference
    darkMode:
      type: boolean
      description: Dark mode preference
    emailNotifications:
      type: boolean
      description: Email notifications preference
    pushNotifications:
      type: boolean
      description: Push notifications preference
    notificationInterval:
      type: string
      enum: [immediate, daily, weekly]
      description: Notification delivery interval

SystemSettings:
  type: object
  properties:
    settings:
      type: array
      items:
        type: object
        properties:
          key:
            type: string
            description: Setting key
          value:
            type: string
            description: Setting value (serialized as string)
          description:
            type: string
            description: Setting description
          createdAt:
            type: string
            format: date-time
          updatedAt:
            type: string
            format: date-time

SystemSetting:
  type: object
  properties:
    key:
      type: string
      description: Setting key
    value:
      type: string
      description: Setting value (can be any type, serialized as string)
    description:
      type: string
      description: Setting description