UserSettings:
  type: object
  properties:
    sprache:
      type: string
      enum: [de, en]
      default: de
      description: Language preference
    dark_mode:
      type: boolean
      default: false
      description: Dark mode preference
    benachrichtigungen_email:
      type: boolean
      default: true
      description: Email notifications preference
    benachrichtigungen_push:
      type: boolean
      default: false
      description: Push notifications preference
    benachrichtigungen_intervall:
      type: string
      enum: [sofort, taeglich, woechentlich]
      default: sofort
      description: Notification delivery interval

UserSettingsUpdate:
  type: object
  properties:
    sprache:
      type: string
      enum: [de, en]
      description: Language preference
    dark_mode:
      type: boolean
      description: Dark mode preference
    benachrichtigungen_email:
      type: boolean
      description: Email notifications preference
    benachrichtigungen_push:
      type: boolean
      description: Push notifications preference
    benachrichtigungen_intervall:
      type: string
      enum: [sofort, taeglich, woechentlich]
      description: Notification delivery interval

SystemSettings:
  type: object
  properties:
    siteTitle:
      type: string
      description: Site title
    logo:
      type: string
      description: Logo URL
    companyName:
      type: string
      description: Company name
    companyAddress:
      type: string
      description: Company address
    companyPhone:
      type: string
      description: Company phone number
    companyEmail:
      type: string
      format: email
      description: Company email address
    vatNumber:
      type: string
      description: VAT number
    defaultLanguage:
      type: string
      enum: [de, en]
      description: Default language
    defaultVatRate:
      type: number
      description: Default VAT rate
    systemEmail:
      type: string
      format: email
      description: System email address
    maintenanceMode:
      type: boolean
      description: Maintenance mode flag
    emailNotifications:
      type: boolean
      description: Email notifications flag

SystemSettingsUpdate:
  type: object
  properties:
    siteTitle:
      type: string
      description: Site title
      minLength: 2
      maxLength: 100
    logo:
      type: string
      description: Logo URL
      maxLength: 255
    companyName:
      type: string
      description: Company name
      minLength: 2
      maxLength: 100
    companyAddress:
      type: string
      description: Company address
      maxLength: 255
    companyPhone:
      type: string
      description: Company phone number
    companyEmail:
      type: string
      format: email
      description: Company email address
    vatNumber:
      type: string
      description: VAT number
      maxLength: 50
    defaultLanguage:
      type: string
      enum: [de, en]
      description: Default language
    defaultVatRate:
      type: number
      minimum: 0
      maximum: 100
      description: Default VAT rate
    systemEmail:
      type: string
      format: email
      description: System email address
    maintenanceMode:
      type: boolean
      description: Maintenance mode flag
    emailNotifications:
      type: boolean
      description: Email notifications flag

BackupSettings:
  type: object
  properties:
    settings:
      type: object
      properties:
        autoBackup:
          type: boolean
          description: Auto backup flag
        frequency:
          type: string
          enum: [taeglich, woechentlich, monatlich]
          description: Backup frequency
        time:
          type: string
          description: Backup time (HH:MM)
        keepCount:
          type: integer
          description: Number of backups to keep
        storageType:
          type: string
          enum: [lokal, s3, ftp]
          description: Backup storage type
        lastBackup:
          type: string
          format: date-time
          description: Last backup timestamp
    backups:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          filename:
            type: string
          size:
            type: integer
          createdAt:
            type: string
            format: date-time
          type:
            type: string
            enum: [auto, manual]

BackupSettingsUpdate:
  type: object
  properties:
    autoBackup:
      type: boolean
      description: Auto backup flag
    frequency:
      type: string
      enum: [taeglich, woechentlich, monatlich]
      description: Backup frequency
    time:
      type: string
      pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
      description: Backup time (HH:MM)
    keepCount:
      type: integer
      minimum: 1
      maximum: 100
      description: Number of backups to keep
    storageType:
      type: string
      enum: [lokal, s3, ftp]
      description: Backup storage type

ManualBackup:
  type: object
  properties:
    description:
      type: string
      description: Optional description
      maxLength: 200